repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: "v0.2.0"
      hooks:
          - id: ruff
            args: ["--fix"]
          - id: ruff-format
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.1.0" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            types_or:
                [
                    javascript,
                    ts,
                    tsx,
                    html,
                    json,
                    css,
                    scss,
                    markdown,
                    rst,
                    yaml,
                ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: mixed-line-ending
            args: ["--fix=lf"]
            types: [text]
          - id: trailing-whitespace
          - id: check-toml
          - id: check-yaml
          - id: check-json
          - id: check-merge-conflict
