[tool.poetry]
name = "codesys-code-gen"
version = "0.1.0"
description = ""
authors = ["John te Bokkel <john@powercoreeng.com>"]

[tool.poetry.dependencies]
python = "^3.8"
attrs = "^21.4.0"
boltons = "^21.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
