"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Optional

"""Codesys data types/type aliases"""
REAL = Optional[float]
LREAL = Optional[float]
DATE_AND_TIME = Optional[datetime]
DT = DATE_AND_TIME
TIME = ...
LTIME = ...
STRING = Optional[str]
WSTRING = Optional[str]
TIME = ...
LTIME = ...
BOOL = Optional[bool]
BYTE = Optional[int]
WORD = Optional[int]
DWORD = Optional[int]
LWORD = Optional[int]
SINT = Optional[int]
USINT = Optional[int]
INT = Optional[int]
UINT = Optional[int]
DINT = Optional[int]
UDINT = Optional[int]
LINT = Optional[int]
ULINT = Optional[int]
UXINT = Optional[int]
XINT = Optional[int]
XWORD = Optional[int]
